import type { Source } from "./contracts";
export const platforms: {id:Source;label:string;account:boolean;placeholder:string;help:string;video:boolean}[] = [
  {id:"instagram",label:"Instagram",account:true,placeholder:"Leave empty for all your saved posts",help:"Paste a post or saved collection link. An empty link downloads your saved posts.",video:true},
  {id:"x",label:"X",account:true,placeholder:"Leave empty for all your bookmarks",help:"Paste a post link. An empty link downloads your bookmarks.",video:true},
  {id:"youtube",label:"YouTube",account:false,placeholder:"https://www.youtube.com/watch?v=...",help:"Public videos, Shorts, explicit playlist links and Watch Later (list=WL). Watch Later and Liked videos need a YouTube browser approval in Accounts; Google identity sign-in alone is separate. A video link saves only that video, even when it includes a playlist. Approve your YouTube browser session in Accounts for videos/playlists your account can access. Live broadcasts and protected media are not supported; authentication does not guarantee extraction.",video:true},
  {id:"facebook",label:"Facebook",account:false,placeholder:"https://www.facebook.com/reel/...",help:"Public video, Reel or watch links. Facebook extraction is limited: some public pages need a compatibility update and cannot currently be read. Browser approval is optional for supported public links. Private content is outside the supported scope. Group browsing and photo-post import are not implemented; some pages still fail due to parser compatibility.",video:true},
  {id:"tiktok",label:"TikTok",account:false,placeholder:"https://www.tiktok.com/@creator/video/...",help:"Public video or photo-post links. Open short share links in your browser and copy the full post address. Only publicly available posts are supported. Private and followers-only content is outside the supported scope.",video:true},
  {id:"pinterest",label:"Pinterest",account:false,placeholder:"https://www.pinterest.com/pin/.../",help:"Public pins and boards, including board sections. Open pin.it links in your browser and copy the full pinterest.com address. Only publicly available pins and boards are supported. Secret boards are outside the supported scope; no Pinterest developer app or OAuth setup is needed.",video:true},
  {id:"discord",label:"Discord",account:false,placeholder:"https://cdn.discordapp.com/attachments/...",help:"In Discord, open an image, video or audio attachment and copy its media link. Paste the attachment link, not a message/channel link. Expired links need a fresh copy. No account connection or server setup is needed. Only the linked media file is downloaded.",video:true},
];
export const platform = (source:Source) => platforms.find(item=>item.id===source)!;
export const platformLabel = (source:Source) => platform(source)?.label ?? "Saved content";
